### ISSUE TITLE
add descriptions to database fields

### ISSUE THREAD

**Issue by ayota** [texas-justice-initiative/jail-population-reports#5]
In the `schema.yml` file we have a listing of all current columns in the database. It would be helpful for the report-specific columns to have some description or discussion of what the numbers mean and how to interpret them, or even just more information about the report in the table descriptions. Don't worry about `data_date`, `processed_at`, `document_id`, `source_filename`, and `report_date` as these are things generated in processing to keep track of when/where the data is from.

For example, to add a description to the `pretrial_felons` column, you would add `description: description text` beneath the `name` field like so:
```
models:
  - name: jail_population_total
    description: Monthly totals for jail populations report
    columns:
    - name: report_date
    - name: pretrial_felons
      description: {YOUR AWESOME DESCRIPTION HERE}
    - name: convicted_felons
    - name: convicted_felons_sentenced_county
```

Some common gotchas/considerations:
- the `description` tag **doesn't** have a - in front of it
- if the description is longer than 1 line, we need to use special formatting (don't worry about it)
- if there's a need to write a few paragraphs, or a description is going to be used in multiple places, we can make a fancier documents file and fill that in

File is available in [`warehouse/models/prep/schema.yml`](https://github.com/texas-justice-initiative/jail-population-reports/blob/develop/warehouse/models/prep/schema.yml)

These descriptions are rendered and available on the [documentation website](https://texas-justice-initiative.github.io/jail-population-reports/#!/overview)
